### ISSUE TITLE
can't fine result using encoder network

### ISSUE THREAD

**Issue by kkang831** [minyoungg/pix2latent#2]
Thank you for sharing your code!! It's a cool work.

Is there a code using encoder network? I can't fine them..

**Comment by minyoungg** [comment]
Thanks! 
The encoder is in the legacy branch but not in the master branch. 

For now you can refer to legacy branch which did use it and try to integrate it in the current codebase. 
https://github.com/minyoungg/pix2latent/tree/legacy

You can see how I loaded it in here
https://github.com/minyoungg/pix2latent/blob/legacy/demo.py#L289-L299

It is in my list of to-dos .. so I will try to get on it soon. :)

**Comment by kkang831** [comment]
Thank you very much!!!
