### ISSUE TITLE
Fine-tuning the weights of generative model?

### ISSUE THREAD

**Issue by Twizwei** [minyoungg/pix2latent#4]
Hi there, excellent job! Thanks for providing the code!

I have a question about fine-tuning. In Section 3.5 of the paper, I think there is a regularization term that can also optimize the weights of the original GAN. Where can I find this part in your code? Currently, I just saw the optimization of z,c, and ф. Did I miss something? Please correct me if I was wrong.

Thank you again!

**Comment by minyoungg** [comment]
There is a fine-tuning procedure in the paper. 
I did not include the fine-tuning but it should be fairly straightforward to implement.
The main meat of the paper is in the optimization and the fine-tuning is just the icing on the cake. 
If you think it would be helpful to be integrated into the codebase I can add it in my next push.

**Comment by Twizwei** [comment]
Yes, that would be helpful! Thank you so much!
